---
version: '2'
services:
  app:
    image: phoenix:1.2.5
    build: .
    ports:
      - "4001:4000"
    volumes:
      - ./:/app
    depends_on:
      - db
  db:
    image: postgres:9
    volumes:
      - ${DOCKER_POSTGRESQL_DATA}:/var/lib/postgresql/data
    ports:
      - "5432:5432"
